//
// Created by bear on 7/5/2022.
//

#ifndef CPPAUTOGRAD_VARIABLE_INCLUDE_VARIABLE_VARIABLE_H
#define CPPAUTOGRAD_VARIABLE_INCLUDE_VARIABLE_VARIABLE_H

#endif //CPPAUTOGRAD_VARIABLE_INCLUDE_VARIABLE_VARIABLE_H
